GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/62223d1555b44beeb905a43c

###
GET http://localhost:3001/api/persons/62262f801ba9b74413583f34


###
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/persons/62262f801ba9b74413583f34

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
  "name": "Billy Bob",
  "number": "2345-2345"
}